version: '3'
services:
  extension-filter-postgres:
    image: yooputer/extension-filter:postgres
    volumes:
      - extension-filter-volume:/var/lib/postgresql/data
    restart: always

  extension-filter-express:
    image: yooputer/extension-filter:express
    depends_on:
      - extension-filter-postgres
    restart: on-failure

  extension-filter-front:
    image: yooputer/extension-filter:front
    ports:
      - 80:3000
    depends_on:
      - extension-filter-express
    restart: on-failure

volumes:
  extension-filter-volume: